{% set name = "pycustomfocus" %}
{% set version = "3.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyCustomFocus-{{ version }}.tar.gz
  sha256: 720cd42cb84148a9b9af3e5727be53d61c68f993a615a3609e37830a4d2c4249

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - config
    - configparser
    - matplotlib-base
    - numpy
    - pydantic
    - pyqt
    - pyqtgraph
    - python >=3.6
    - qdarkstyle
    - qtpy
    - scipy
    - tqdm

test:
  imports:
    - PyFocus
    - PyFocus.sim
    - PyFocus.VP_functions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/PyCustomFocus
  summary: Full vectorial calculation of focused electromagnetic fields moduled by a custom phase mask
  license: MIT
  license_file: LICENCE.txt
  dev_url: https://github.com/fcaprile/PyFocus

extra:
  recipe-maintainers:
    - jaimergp
    - goanpeca
