{% set name = "pycustomfocus" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyCustomFocus-{{ version }}.tar.gz
  sha256: 7418c3a7474f95c340992f4dc6b11e2e807e001f60ba82caecb2b846b3e28d16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - qdarkstyle
    - config
    - tqdm
    - matplotlib-base
    - pyqt
    - qtpy
    - pyqtgraph
    - configparser

test:
  imports:
    - PyFocus
    - PyFocus.sim
    - PyFocus.VP_functions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fcaprile/PyFocus
  summary: Full vectorial calculation of focused electromagnetic fields moduled by a custom phase mask
  license: MIT
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - jaimergp
    - goanpeca
