{% set name = "pycustomfocus" %}
{% set version = "3.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyCustomFocus-{{ version }}.tar.gz
  sha256: 92740aa19f250a7b9e0355e25d69287a4698d46f9ee2a96045963e2c25627b6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - config
    - configparser
    - matplotlib-base
    - numpy
    - pydantic
    - python >=3.6
    - pyqt
    - pyqtgraph
    - qdarkstyle
    - qtpy
    - scipy
    - tqdm

test:
  imports:
    - PyFocus
    - PyFocus.custom_dataclasses
    - PyFocus.custom_typing
    - PyFocus.equations
    - PyFocus.helpers
    - PyFocus.model
    - PyFocus.napari_adapter
    - PyFocus.plot_functions
    - PyFocus.user_interface
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/PyCustomFocus
  summary: Full vectorial calculation of focused electromagnetic fields moduled by a custom phase mask
  license: MIT
  license_file: LICENCE.txt
  dev_url: https://github.com/fcaprile/PyFocus

extra:
  recipe-maintainers:
    - jaimergp
    - goanpeca
